import type { RedditBookmark } from "../types/bookmark";

export const MOCK_BOOKMARKS: RedditBookmark[] = [
  {
    id: "1",
    title: "A quiet corner of the internet",
    subreddit: "r/webdev",
    source: "Pinterest",
    author: "u/quiet_explorer",
    createdAt: "2 hours ago",
    dateStr: "Jul 7",
    score: 1420,
    numComments: 184,
    permalink: "https://reddit.com",
    url: "https://pinterest.com",
    thumbnail: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80",
    postType: "image",
    selftext: "The web still has beautiful, weird places if you know where to look.",
    tags: ["Weekend Watch", "productivity"],
  },
  {
    id: "2",
    title: "Tailwind CSS v4.0 is officially released with a brand new engine!",
    subreddit: "r/reactjs",
    source: "Reddit",
    author: "u/frontend_dev",
    createdAt: "5 hours ago",
    dateStr: "Aug 2",
    score: 856,
    numComments: 312,
    permalink: "https://reddit.com",
    url: "https://tailwindcss.com",
    thumbnail: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=600&q=80",
    postType: "image",
    selftext: "Discover how the zero-config engine speeds up build times by over 10x with native CSS variables.",
    tags: ["Release", "css"],
  },
  {
    id: "3",
    title: "Building real-time layout engines with WebAssembly and Rust",
    subreddit: "r/programming",
    source: "GitHub",
    author: "u/rustacean",
    createdAt: "1 day ago",
    dateStr: "Aug 1",
    score: 2310,
    numComments: 95,
    permalink: "https://reddit.com",
    url: "https://github.com",
    thumbnail: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=600&q=80",
    postType: "link",
    selftext: "An in-depth guide on compiling Rust layout calculators into high-performance WASM binaries.",
    tags: ["Architecture", "rust"],
  },
  {
    id: "4",
    title: "Minimalist UI Architecture for Modern Web Applications",
    subreddit: "r/design",
    source: "Dribbble",
    author: "u/ui_craft",
    createdAt: "2 days ago",
    dateStr: "Jul 28",
    score: 1140,
    numComments: 67,
    permalink: "https://reddit.com",
    url: "https://dribbble.com",
    thumbnail: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=600&q=80",
    postType: "image",
    selftext: "Exploring micro-interactions, dark mode color harmonies, and accessible typography scale.",
    tags: ["UI/UX", "design"],
  },
  {
    id: "5",
    title: "Mastering React 19 Server Components and Suspense",
    subreddit: "r/reactjs",
    source: "Medium",
    author: "u/react_master",
    createdAt: "4 days ago",
    dateStr: "Jul 24",
    score: 1980,
    numComments: 142,
    permalink: "https://reddit.com",
    url: "https://medium.com",
    thumbnail: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?auto=format&fit=crop&w=600&q=80",
    postType: "text",
    selftext: "Practical patterns for streaming SSR and client state synchronization without hydration mismatches.",
    tags: ["React", "frontend"],
  },
  {
    id: "6",
    title: "Designing Calm Interfaces in a Hyper-Connected World",
    subreddit: "r/webdesign",
    source: "Substack",
    author: "u/mindful_tech",
    createdAt: "1 week ago",
    dateStr: "Jul 15",
    score: 740,
    numComments: 38,
    permalink: "https://reddit.com",
    url: "https://substack.com",
    thumbnail: "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=600&q=80",
    postType: "image",
    selftext: "Why distraction-free layouts and soft color palettes improve user focus and cognitive retention.",
    tags: ["Productivity", "calm"],
  },
];
